/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peliculas;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author fam. moreno
 */
public class Pelicula extends javax.swing.JFrame {

    /**
     * Creates new form Pelicula
     */
    public Pelicula() {
        initComponents();
        this.setLocationRelativeTo(this);
        Conexion.conectar();
        cbxDirectorSalida.setEnabled(false);
       cbxProduccionSalida.setEnabled(false);
       cbxGeneroSalida.setEnabled(false);
       cbxEdadSalida.setEnabled(false);
       ArrayList <String> lista = new  ArrayList<String>();
       lista = Conexion.llenar_combobox("director","Nombre_productor");
       ArrayList <String> lista1 = new  ArrayList<String>();
        lista1 = Conexion.llenar_combobox("productora","Nombre_Productora");
        ArrayList <String> lista2 = new  ArrayList<String>();
        lista2 = Conexion.llenar_combobox("genero","Tipo_de_genero");
        ArrayList <String> lista3 = new  ArrayList<String>();
        lista3 = Conexion.llenar_combobox("clasificacion_edad","Cod_Clasificacion");
        for(int i=0;i<lista.size();i++){
        cbxDirector.addItem(lista.get(i));
        cbxDirectorSalida.addItem(lista.get(i));
        
        }
         for(int i=0;i<lista1.size();i++){
        cbxProduccion.addItem(lista1.get(i));
        cbxProduccionSalida.addItem(lista1.get(i));
        }
          for(int i=0;i<lista2.size();i++){
        cbxGenero.addItem(lista2.get(i));
        cbxGeneroSalida.addItem(lista2.get(i));
        }
           for(int i=0;i<lista3.size();i++){
        cbxEdad.addItem(lista3.get(i));
        cbxEdadSalida.addItem(lista3.get(i));
        }
   
        
    }
    private Variables dar_valores_modificados() {
       Variables x = null;
        String Nombre = txtNombreModificar.getText();
        String Sinopsis = txtSinopsisModificacion.getText();
        String Director = cbxDirectorSalida.getSelectedItem().toString();
        String Productora = cbxProduccionSalida.getSelectedItem().toString();
        String Genero = cbxGeneroSalida.getSelectedItem().toString();
        String Edad = cbxEdadSalida.getSelectedItem().toString();
        
        x = new Variables(Nombre,Sinopsis,Director,Productora,Genero,Edad);
        return x; 
    }
    public Variables dar_valores(){
    Variables x = null;
    
    if( cbxDirector.getSelectedIndex()==0 || cbxProduccion.getSelectedIndex()==0 || cbxGenero.getSelectedIndex()==0 || cbxEdad.getSelectedIndex()==0){
        System.out.println("no se puede dejar en blanco los combobox");
    }else{
        String Nombre = txtNombreIngresar.getText();
        String Sinopsis = txtASinopsisIngresar.getText();
        String Director = cbxDirector.getSelectedItem().toString();
        String Productora = cbxProduccion.getSelectedItem().toString();
        String Genero = cbxGenero.getSelectedItem().toString();
        String Edad = cbxEdad.getSelectedItem().toString();
    
        
        x = new Variables(Nombre,Sinopsis,Director,Productora,Genero,Edad);
        return x;
    }
        return x;
    }
    public void mostrar(Variables resultado){
    txtDirectorSalida.setText(resultado.getDirector());
    txtProduccionSalida.setText(resultado.getProductora());
    txtGeneroSalida.setText(resultado.getGenero());
    txtEdadSalida.setText(resultado.getEdad());
    txtSinopsisSalida.setText(resultado.getSinopsis());
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtASinopsisIngresar = new javax.swing.JTextArea();
        cbxGenero = new javax.swing.JComboBox<>();
        cbxProduccion = new javax.swing.JComboBox<>();
        cbxDirector = new javax.swing.JComboBox<>();
        cbxEdad = new javax.swing.JComboBox<>();
        txtNombreIngresar = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnAggDirector = new javax.swing.JButton();
        btnAggProduccion = new javax.swing.JButton();
        btnAggGenero = new javax.swing.JButton();
        btnAggEdad = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSinopsisSalida = new javax.swing.JTextArea();
        txtDirectorSalida = new javax.swing.JTextField();
        txtProduccionSalida = new javax.swing.JTextField();
        txtGeneroSalida = new javax.swing.JTextField();
        txtEdadSalida = new javax.swing.JTextField();
        btnLimpiarBuscar = new javax.swing.JButton();
        btnCerrarBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNombreBorrar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnCerrarBorrar = new javax.swing.JButton();
        btnLimpiarBorrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnGuardarModificacion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCerrarEditar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtNombreModificar = new javax.swing.JTextField();
        cbxDirectorSalida = new javax.swing.JComboBox<>();
        cbxProduccionSalida = new javax.swing.JComboBox<>();
        cbxGeneroSalida = new javax.swing.JComboBox<>();
        cbxEdadSalida = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSinopsisModificacion = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Myriad Hebrew", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese los datos necesarios para poder guardar la pelicula");

        jLabel2.setText("Nombre");

        jLabel3.setText("Director");

        jLabel4.setText("Produccion");

        jLabel5.setText("Sinopsis");

        jLabel6.setText("Genero");

        jLabel7.setText("Categoria de edad");

        jLabel8.setText("Agrege una pequeña sinopsis");

        txtASinopsisIngresar.setColumns(20);
        txtASinopsisIngresar.setRows(5);
        txtASinopsisIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtASinopsisIngresarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtASinopsisIngresarKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtASinopsisIngresar);

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona..." }));
        cbxGenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxGeneroKeyPressed(evt);
            }
        });

        cbxProduccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona..." }));
        cbxProduccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxProduccionKeyPressed(evt);
            }
        });

        cbxDirector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona..." }));
        cbxDirector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxDirectorKeyPressed(evt);
            }
        });

        cbxEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona..." }));
        cbxEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxEdadKeyPressed(evt);
            }
        });

        txtNombreIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreIngresarActionPerformed(evt);
            }
        });
        txtNombreIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreIngresarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreIngresarKeyTyped(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 204, 153));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 204, 153));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnAggDirector.setBackground(new java.awt.Color(0, 204, 153));
        btnAggDirector.setText("Nuevo Director");
        btnAggDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggDirectorActionPerformed(evt);
            }
        });

        btnAggProduccion.setBackground(new java.awt.Color(0, 204, 153));
        btnAggProduccion.setText("Nueva Produccion");
        btnAggProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggProduccionActionPerformed(evt);
            }
        });

        btnAggGenero.setBackground(new java.awt.Color(0, 204, 153));
        btnAggGenero.setText("Nuevo Genero");
        btnAggGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggGeneroActionPerformed(evt);
            }
        });

        btnAggEdad.setBackground(new java.awt.Color(0, 204, 153));
        btnAggEdad.setText("Nueva edad");
        btnAggEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggEdadActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(0, 204, 153));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxGenero, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbxProduccion, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbxEdad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbxDirector, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNombreIngresar, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnAggProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAggDirector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAggGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAggEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAggDirector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAggProduccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAggGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAggEdad))
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Insertar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setText("Ingrese el nombre de la pelicula para buscar sus datos");

        jLabel10.setText("Nombre");

        txtNombreBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscarActionPerformed(evt);
            }
        });
        txtNombreBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreBuscarKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel11.setText("Director");

        jLabel12.setText("Produccion");

        jLabel13.setText("Genero");

        jLabel14.setText("Categoria de edad");

        jLabel15.setText("Sinopsis");

        txtSinopsisSalida.setColumns(20);
        txtSinopsisSalida.setRows(5);
        txtSinopsisSalida.setEnabled(false);
        jScrollPane2.setViewportView(txtSinopsisSalida);

        txtDirectorSalida.setEnabled(false);

        txtProduccionSalida.setEnabled(false);

        txtGeneroSalida.setEnabled(false);

        txtEdadSalida.setEnabled(false);

        btnLimpiarBuscar.setText("Limpiar");
        btnLimpiarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBuscarActionPerformed(evt);
            }
        });

        btnCerrarBuscar.setText("Cerrar");
        btnCerrarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEdadSalida, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGeneroSalida, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProduccionSalida, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDirectorSalida, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpiarBuscar))))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarBuscar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDirectorSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProduccionSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneroSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtEdadSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnCerrarBuscar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel16.setText("Ingrese el nombre de la pelicula que desea eliminar");

        jLabel17.setText("Nombre");

        txtNombreBorrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreBorrarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreBorrarKeyTyped(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCerrarBorrar.setText("Cerrar");
        btnCerrarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarBorrarActionPerformed(evt);
            }
        });

        btnLimpiarBorrar.setText("Limpiar");
        btnLimpiarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrarBorrar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLimpiarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(172, 172, 172)
                                    .addComponent(jLabel16))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNombreBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(btnEliminar))))
                        .addGap(0, 208, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel16)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtNombreBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(btnCerrarBorrar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Borrar", jPanel3);

        btnGuardarModificacion.setText("Guardar");
        btnGuardarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModificacionActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCerrarEditar.setText("Cerrar");
        btnCerrarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarEditarActionPerformed(evt);
            }
        });

        jLabel18.setText("Ingrese el nombre de la pelicula que desea modificar de a \"buscar\" y luego modifique los campos");

        jLabel19.setText("Nombre");

        jLabel20.setText("Director");

        jLabel21.setText("Produccion");

        jLabel22.setText("Genero");

        jLabel23.setText("Categoria de edad");

        jLabel24.setText("Sinopsis");

        txtNombreModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreModificarActionPerformed(evt);
            }
        });
        txtNombreModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreModificarKeyTyped(evt);
            }
        });

        txtSinopsisModificacion.setColumns(20);
        txtSinopsisModificacion.setRows(5);
        jScrollPane3.setViewportView(txtSinopsisModificacion);

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardarModificacion)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarEditar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel18))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxGeneroSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxEdadSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(txtNombreModificar)
                                    .addComponent(cbxDirectorSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxProduccionSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)))
                        .addGap(93, 93, 93)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtNombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbxDirectorSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cbxProduccionSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cbxGeneroSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbxEdadSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarModificacion)
                    .addComponent(jButton2)
                    .addComponent(btnCerrarEditar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreIngresarActionPerformed

    private void btnAggProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggProduccionActionPerformed
        String Nombre = JOptionPane.showInputDialog("Ingrese el nombre del director de la productora de Peliculas");
        String q = "INSERT INTO `productora` (`Nombre_Productora`) VALUES ('"+Nombre+"')";
        Conexion.ejecutar(q);
    }//GEN-LAST:event_btnAggProduccionActionPerformed

    private void txtNombreBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Variables x;
        x=dar_valores();
        if(x==null){
        JOptionPane.showMessageDialog(null,"No se puede dejar sin selexionar las caracteristicas de los combobox");
        }else{
        Conexion.guardar(x);
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String Nombre;
       Nombre = txtNombreBuscar.getText();
       Variables resultado = Conexion.BuscarPeli(Nombre);
       if(resultado==null){
       }else{
       mostrar(resultado);
       }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombreModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreModificarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       cbxDirectorSalida.setEnabled(true);
       cbxProduccionSalida.setEnabled(true);
       cbxGeneroSalida.setEnabled(true);
       cbxEdadSalida.setEnabled(true);
       String Nombre;
       Nombre = txtNombreModificar.getText();
       Variables resultado = Conexion.BuscarPeli(Nombre);
       if(resultado==null){
       }else{
           
       for(int i = 0; i < (cbxDirectorSalida.getItemCount()-1);i++){
           String valor = cbxDirectorSalida.getItemAt(i);
           
           if(resultado.getDirector().endsWith(valor)){
           cbxDirectorSalida.setSelectedIndex(i);
           }
       }
       for(int i = 0; i < (cbxProduccionSalida.getItemCount()-1);i++){
           String valor = cbxProduccionSalida.getItemAt(i);
           
           if(resultado.getProductora().endsWith(valor)){
           cbxProduccionSalida.setSelectedIndex(i);
           }
       }
       for(int i = 0; i < (cbxGeneroSalida.getItemCount()-1);i++){
           String valor = cbxGeneroSalida.getItemAt(i);
           
           if(resultado.getGenero().endsWith(valor)){
           cbxGeneroSalida.setSelectedIndex(i);
           }
       }
       for(int i = 0; i < (cbxEdadSalida.getItemCount()-1);i++){
           String valor = cbxEdadSalida.getItemAt(i);
           
           if(resultado.getEdad().endsWith(valor)){
           cbxEdadSalida.setSelectedIndex(i);
           }
       }
       txtSinopsisModificacion.setText(resultado.getSinopsis());
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnGuardarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModificacionActionPerformed
       Variables x;
        x=dar_valores_modificados();
        Conexion.guardar(x);
    }//GEN-LAST:event_btnGuardarModificacionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String Nombre = txtNombreBorrar.getText();
        
        int respuesta = JOptionPane.showConfirmDialog(null, "Esta seguro de querer eliminar la pelicula "+Nombre);
        if(respuesta==JOptionPane.YES_OPTION){
        Conexion.eliminar_reg(Nombre);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarEditarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnCerrarEditarActionPerformed

    private void btnCerrarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarBorrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarBorrarActionPerformed

    private void btnCerrarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarBuscarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNombreIngresar.setText(null);
        txtASinopsisIngresar.setText(null);
        cbxDirector.setSelectedIndex(0);
        cbxProduccion.setSelectedIndex(0);
        cbxGenero.setSelectedIndex(0);
        cbxEdad.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnLimpiarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBuscarActionPerformed
       txtNombreBuscar.setText(null);
        txtSinopsisSalida.setText(null);
        txtDirectorSalida.setText(null);
        txtProduccionSalida.setText(null);
        txtGeneroSalida.setText(null);
        txtEdadSalida.setText(null);
    }//GEN-LAST:event_btnLimpiarBuscarActionPerformed

    private void btnLimpiarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBorrarActionPerformed
        txtNombreBorrar.setText(null);
    }//GEN-LAST:event_btnLimpiarBorrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtNombreModificar.setText(null);
        txtSinopsisModificacion.setText(null);
        cbxDirectorSalida.setSelectedIndex(0);
        cbxProduccionSalida.setSelectedIndex(0);
        cbxGeneroSalida.setSelectedIndex(0);
        cbxEdadSalida.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNombreIngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreIngresarKeyTyped
        int limite = 44;
        if(txtNombreIngresar.getText().length()==limite){
            JOptionPane.showMessageDialog(null, "Llego al limite de letras para el nombre de la pelicula");
        evt.consume();
        cbxDirector.requestFocus();
        }
        
        
    }//GEN-LAST:event_txtNombreIngresarKeyTyped

    private void txtASinopsisIngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtASinopsisIngresarKeyTyped
        int limite = 100;
        if(txtNombreIngresar.getText().length()==limite){
            JOptionPane.showMessageDialog(null, "Llego al limite de letras para el nombre de la pelicula");
        evt.consume();
        btnGuardar.requestFocus();
        }
        
    }//GEN-LAST:event_txtASinopsisIngresarKeyTyped

    private void txtNombreIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreIngresarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        cbxDirector.requestFocus();
        }
    }//GEN-LAST:event_txtNombreIngresarKeyPressed

    private void txtASinopsisIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtASinopsisIngresarKeyPressed
        
    }//GEN-LAST:event_txtASinopsisIngresarKeyPressed

    private void cbxDirectorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxDirectorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        cbxProduccion.requestFocus();
        }
    }//GEN-LAST:event_cbxDirectorKeyPressed

    private void cbxProduccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxProduccionKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        cbxGenero.requestFocus();
        }
    }//GEN-LAST:event_cbxProduccionKeyPressed

    private void cbxGeneroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxGeneroKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        cbxEdad.requestFocus();
        }
    }//GEN-LAST:event_cbxGeneroKeyPressed

    private void cbxEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxEdadKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        txtASinopsisIngresar.requestFocus();
        }
    }//GEN-LAST:event_cbxEdadKeyPressed

    private void txtNombreBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBuscarKeyTyped
        int limite = 44;
        if(txtNombreBuscar.getText().length()==limite){
            JOptionPane.showMessageDialog(null, "Llego al limite de letras para el nombre de la pelicula");
        evt.consume();
        
        }
    }//GEN-LAST:event_txtNombreBuscarKeyTyped

    private void txtNombreBorrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBorrarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        btnEliminar.requestFocus();
        }
    }//GEN-LAST:event_txtNombreBorrarKeyPressed

    private void txtNombreModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreModificarKeyTyped
        int limite = 44;
        if(txtNombreModificar.getText().length()==limite){
            JOptionPane.showMessageDialog(null, "Llego al limite de letras para el nombre de la pelicula");
        evt.consume();
        
        }
    }//GEN-LAST:event_txtNombreModificarKeyTyped

    private void txtNombreBorrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBorrarKeyTyped
        int limite = 44;
        if(txtNombreBorrar.getText().length()==limite){
            JOptionPane.showMessageDialog(null, "Llego al limite de letras para el nombre de la pelicula");
        evt.consume();
        
        }
    }//GEN-LAST:event_txtNombreBorrarKeyTyped

    private void btnAggDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggDirectorActionPerformed
        String NombreDirector = JOptionPane.showInputDialog("Ingrese el nombre del director de peliculas");
        String q = "INSERT INTO `director` (`Nombre_productor`) VALUES ('"+NombreDirector+"')";
        Conexion.ejecutar(q);
        this.repaint();
    }//GEN-LAST:event_btnAggDirectorActionPerformed

    private void btnAggGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggGeneroActionPerformed
        String NombreDirector = JOptionPane.showInputDialog("Ingrese el nombre del director de peliculas");
        String q = "INSERT INTO `genero` (`Tipo_de_genero`) VALUES ('"+NombreDirector+"')";
        Conexion.ejecutar(q);
    }//GEN-LAST:event_btnAggGeneroActionPerformed

    private void btnAggEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggEdadActionPerformed
        String NombreDirector = JOptionPane.showInputDialog("Ingrese el codigo de clasificacion de edad por ejempo +18");
        String Codigo = JOptionPane.showInputDialog("Agrege una pequeña descripcion de la clasificacion");
        String q = "INSERT INTO `clasificacion_edad` (`Cod_Clasificacion`, `Edad_Clasificacion`) VALUES ('"+Codigo+"', '"+NombreDirector+"')";
        Conexion.ejecutar(q);
        this.update(cbxDirector);
    }//GEN-LAST:event_btnAggEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggDirector;
    private javax.swing.JButton btnAggEdad;
    private javax.swing.JButton btnAggGenero;
    private javax.swing.JButton btnAggProduccion;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCerrarBorrar;
    private javax.swing.JButton btnCerrarBuscar;
    private javax.swing.JButton btnCerrarEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarModificacion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarBorrar;
    private javax.swing.JButton btnLimpiarBuscar;
    private javax.swing.JComboBox<String> cbxDirector;
    private javax.swing.JComboBox<String> cbxDirectorSalida;
    private javax.swing.JComboBox<String> cbxEdad;
    private javax.swing.JComboBox<String> cbxEdadSalida;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JComboBox<String> cbxGeneroSalida;
    private javax.swing.JComboBox<String> cbxProduccion;
    private javax.swing.JComboBox<String> cbxProduccionSalida;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtASinopsisIngresar;
    private javax.swing.JTextField txtDirectorSalida;
    private javax.swing.JTextField txtEdadSalida;
    private javax.swing.JTextField txtGeneroSalida;
    private javax.swing.JTextField txtNombreBorrar;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtNombreIngresar;
    private javax.swing.JTextField txtNombreModificar;
    private javax.swing.JTextField txtProduccionSalida;
    private javax.swing.JTextArea txtSinopsisModificacion;
    private javax.swing.JTextArea txtSinopsisSalida;
    // End of variables declaration//GEN-END:variables

    private void update(JComboBox<String> cbxDirector) {
       
    }

    
}
